### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by yarmoliq** [bogomazdmitry/calculator-stm32f4#2]
- [x] display clears it self on `void display(char[8])` call
- [x] remove pin defines in `.h` files and create a structure to configure them
- [x] `void display(char[8])` -> `void display(uint8_t[8])`
- [x] refactor number creation method

**Comment by bogomazdmitry** [comment]
Fix part in https://github.com/bogomazdmitry/calculator-stm32f4/commit/c65bcf67fab29fa42dad8b793831f53872ad2464 and https://github.com/bogomazdmitry/calculator-stm32f4/commit/8679879a083beb873a3ab2f83f51f6600c90cf21
